const mysql = require("./model/db");
//test
const date = new Date("2015-02-03");
(async () => {
    await mysql.createUser("Ang, Helen", "admin", "sycn", "123", date, "active");
    mysql.createProduct("PingPong", "table tennis", "paddle", "supplier", "active", 100, 150); 
    mysql.createStockEntry("branch1", date, 100, 1234, 1, 1); 
    mysql.createStockWithdrawal(date, 3, "damaged", 1, 1, 1);
    mysql.createOrders(0.2, "Amira", 1); 
    mysql.createOrderInfo(3, 1, 1); 
    mysql.createReturnExchange(date, "refunded", 1, 1, 1); 
    mysql.createReturnExchangeInfo(1, 2, 1, 2, "damaged", 1); 
    mysql.createReturnExchangeInfo(1, 1, null, null, "damaged", 1); 
    mysql.getUsers();
    mysql.getUserById(1);
    mysql.getUserById(2);
    mysql.getUserById(99);
    mysql.getProducts();
    const result = await mysql.getProductById(1);
    console.log(result.productName);
    mysql.getStockEntries();
    mysql.getStockEntryById(1);
    mysql.getStockWithdrawals();
    mysql.getStockWithdrawalById(1);
    mysql.getOrders();
    mysql.getOrderById(1);
    mysql.getOrderInfo();
    mysql.getOrderInfoById(1);
    mysql.getReturnExchanges();
    mysql.getReturnExchangeById(1);
    mysql.getReturnExchangeInfo();
    mysql.getReturnExchangeInfoById(1);
})();
